import:
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-base-r4.1.yml
    mode: deep_merge_prepend
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-dom0-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-vms-r4.1.yml
language: python
python: '3.7'
services:
  - xvfb
  - docker
jobs:
  include:
    - name: pylint
      install:
       - docker build -t qrexec-test ci
      env: DOCKER_RUN="docker run -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR -w $TRAVIS_BUILD_DIR -- qrexec-test"
      script:
       - $DOCKER_RUN pylint qrexec
    - name: run-tests
      install:
       - pip install --quiet codecov
       - pip install --quiet 'coverage<5.0'
       - docker build -t qrexec-test ci
      env: DOCKER_RUN="docker run -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR -v /tmp/.X11-unix:/tmp/.X11-unix -w $TRAVIS_BUILD_DIR -e DISPLAY=$DISPLAY -- qrexec-test"
      script:
       - $DOCKER_RUN ./run-tests
       # use gcov from within the container
       - $DOCKER_RUN find . -type f -name '*.gcno'  -execdir gcov -pb  {} +
       - find . -type f -name '*.gcno'  -exec rm  {} +
    - name: fuzz
      install:
       - sudo apt-get -y install clang
      script:
       - make -C fuzz test
    - stage: deploy
      python: '3.6'
      script: ~/qubes-builder/scripts/travis-deploy
after_success:
  - codecov
